### PR TITLE
Upgraded the real way now

### PR DESCRIPTION
**Pull request by Indigenuity**
Left out checksum changes.  Just copy/pasted from the [actual tap](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb) this time.  Pain in the ass though

### CODE REVIEW

**Comment by MasterDDT** [comment]
Maybe @nitay @danielheyman have ideas how to make this better

**Comment by JaceTSM** [comment]
nvm, it's good.

**Comment by Indigenuity** [comment]
solved conflict, doesn't seem to be updating status

**Comment by danielheyman** [comment]
@Indigenuity @JaceTSM since we are not after a specific version of terraform, it might make sense to just use the terraform from the brew tap. It's generally a very safe source to pull from.

**Comment by Indigenuity** [comment]
well we do want to stick to a specific version for the very reason I had to update this.  Everybody has to upgrade in sync or else some people can't update things

**Comment by danielheyman** [comment]
got it! copying directly from the brew taps, as you did, is the easiest strategy then

**Comment by Indigenuity** [comment]
If i can get GH to say the check is resolved

**Pull request merged**
